[versions]
compileSdk = "35"
targetSdk = "35"
agp = "8.9.2"
buildToolsVersion = "36.0.0"
kotlin = "2.2.0"
compose-bom = "2025.07.00"
navigationcompose = "2.9.3"
lifecycle = "2.9.2"
activitycompose = "1.10.1"
activity = "1.10.1"
coroutines = "1.10.2"
accompanist = "0.34.0"
room = "2.7.2"
okhttp = "5.1.0"
moshi = "1.15.2"
jsoup = "1.21.1"
chiptextfield = "0.7.0-alpha05"
sheets = "0.6.0-alpha05"
expandabletext = "0.4.0"
flick = "1.7.0"
fresco = "3.2.0"
media3 = "1.7.1"
ksp = "2.2.0-2.0.2"
sonner = "0.3.8"
androidx-benchmark = "1.2.4"
quickjs-kt = "1.0.0-alpha13"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material3 = { module = "androidx.compose.material3:material3" }

androidx-core = { module = "androidx.core:core", version = "1.13.1" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activitycompose" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = " androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationcompose" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version = "1.1.0-alpha01" }
androidx-browser = { module = "androidx.browser:browser", version = "1.8.0" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version = "1.0.1" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version = "1.3.1" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version = "1.0.0" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version = "1.0.0" }

androidx-benchmark-common = { module = "androidx.benchmark:benchmark-common", version.ref = "androidx-benchmark" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }

androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version = "2.3.0" }

junit = { module = "junit:junit", version = "4.13.2" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

turbine = { module = "app.cash.turbine:turbine", version = "1.1.0" }

accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }

barcodeScanning = { module = "com.google.mlkit:barcode-scanning", version = "17.2.0" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
fresco-animated-base = { module = "com.facebook.fresco:animated-base", version.ref = "fresco" }
fresco-gif = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
fresco-webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }
fresco-middleware = { module = "com.facebook.fresco:middleware", version.ref = "fresco" }
fresco-imagepipeline-okhttp = { module = "com.facebook.fresco:imagepipeline-okhttp3", version.ref = "fresco" }

media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3-database = { module = "androidx.media3:media3-database", version.ref = "media3" }
media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3" }

guava = { module = "com.google.guava:guava", version = "31.1-android" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

disklrucache = { module = "com.jakewharton:disklrucache", version = "2.0.2" }

sheets = { module = "io.github.dokar3:sheets", version.ref = "sheets" }

chiptextfield = { module = "io.github.dokar3:chiptextfield", version.ref = "chiptextfield" }

expandabletext = { module = "io.github.dokar3:expandabletext", version.ref = "expandabletext" }

sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }

quickjs-kt = { module = "io.github.dokar3:quickjs-kt", version.ref = "quickjs-kt" }
quickjs-kt-converter-moshi = { module = "io.github.dokar3:quickjs-kt-converter-moshi", version.ref = "quickjs-kt" }

subsamplingimageview = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version = "3.10.0" }

flick = { module = "me.saket:flick", version.ref = "flick" }

crc = { module = "com.github.snksoft:crc", version = "1.1.0" }

commonmark = { module = "org.commonmark:commonmark", version = "0.22.0" }

semver = { module = "com.vdurmont:semver4j", version = "3.1.0" }

bolts-tasks = { module = "com.parse.bolts:bolts-tasks", version = "1.4.0" }
